#!/bin/bash
    
set -euo pipefail

SOFT="$(basename $0)"

cleanup (){
    :
}

trap cleanup EXIT

openssl req -x509 -out localhost.crt -keyout localhost.key \
  -newkey rsa:2048 -nodes -sha256 \
  -subj '/CN=localhost' -extensions EXT -config <( \
   printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
openssl pkcs12 -export -in localhost.crt -inkey localhost.key -out localhost.p12
chmod +r localhost.p12
