#!/usr/bin/env bash

set -euo pipefail

candidatesFiles=(
    .commitlintrc
    .commitlintrc.json
    .commitlintrc.yaml
    .commitlintrc.yml
    .commitlintrc.js
    .commitlintrc.cjs
    .commitlintrc.ts
    commitlint.config.js
    commitlint.config.cjs
    commitlint.config.ts
)

volume=()

for file in "${candidatesFiles[@]}"; do
    if [ -f "$file" ]; then
        volume=(--volume "$PWD/$file:/app/$file:ro")
        break
    fi
done

docker run --rm -i "${volume[@]}" pag/commitlint
