#!/bin/bash
    
set -euo pipefail

SOFT="$(basename $0)"
random=$(( ( RANDOM % 100000 ) ))
tempfolder="/tmp/$SOFT/$random"

mkdir -p "$tempfolder"
pushd "$tempfolder" > /dev/null
cleanup (){
    popd > /dev/null
    rm -rf -- ${tempfolder}
}

trap cleanup EXIT
site="$1"

wget --spider --recursive --no-verbose --output-file=wgetlot.txt "$site"
cat wgetlot.txt | tail -n +2  | sed 's/:$//'  | url_matcher
