#!/bin/bash
    
set -euo pipefail

SOFT="$(basename $0)"
random=$(( ( RANDOM % 100000 ) ))
tempfolder="/tmp/$SOFT/$random"

mkdir -p "$tempfolder"
pushd "$tempfolder" > /dev/null
cleanup (){
    popd > /dev/null
    rm ${tempfolder}
}

#trap cleanup EXIT
site="$1"

wget --spider --recursive --no-verbose --output-file=wgetlot.txt "$site"
sed -n "s@.\+ URL:\([^ ]\+\) .\+@\1@p" wgetlog.txt | sed "s@&@\&amp;@" > sedlog.txt

cat sedlog.txt
