#!/usr/bin/env bash

set -euo pipefail

SOFT=$(basename "$0")

while (( $# )); do
    case "$1" in
        arch)
        shift
        folder=$1
        shift
        cd src
        mkdir -p "$folder"
        cd "$folder"
        mkdir -p {Domain,Infrastructure,Application}
        touch {Domain,Infrastructure,Application}/.gitignore
        git add .
        exit
        ;;
        *)
        >&2 echo "$SOFT: unknown command $*"
        exit 1
        shift
            ;;
    esac
done
