#!/usr/bin/env bash

set -euo pipefail

SOFT=$(basename "$0")

while (( $# )); do
    case "$1" in
        *)
        >&2 echo "$SOFT: unknown command $*"
        exit 1
        shift
            ;;
    esac
done
