#!/bin/bash

usage(){
    echo "Usage: $(basename "$0") -[0123456789] message"
}

arguments=()

LOG_LEVEL="${LOG_LEVEL:=4}"
current=9
do_printf=false
while [ "$#" -gt 0  ]; do
    case "$1" in
        -[012345678])
            current="${1:1}"
            ;;
        "-h" | "--help")
            usage
            exit
            ;;
        "-q" | "--quiet")
            exec > /dev/null
            ;;
        "-d")
            echo "${LOG_LEVEL}"
            exit
            ;;
        "--printf")
            do_printf=true
            ;;
        "--")
            shift
            arguments+=("$@")
            set --
            break;
            ;;
        "-"*)
            if [ "${#1}" -eq 1 ]; then
                echo "Invalid token -" >&2
                exit 1
            fi
            if [ "${#1}" -eq 2 ]; then
                echo "unknown option $1" >&2
                exit 2
            fi
            first=${1:1:1}
            rest=${1:2}
            shift
            set -- -"$first" -"$rest" "$@"
            continue
            ;;
        *)
            arguments+=("$1")
            ;;
    esac
    shift
done

set -- "${arguments[@]}"

if [ ! "$LOG_LEVEL" -lt "$current" ]; then
    if "$do_printf"; then
        printf "${@}"
    else
        echo "$@"
    fi
fi
