#!/usr/bin/env bash

args=()

user="--user $(id -u):$(id -g)"
docker=

while (( $# )); do
  case "$1" in
    --root)
      user=
      ;;
    --docker)
      docker="-v /var/run/docker.sock:/var/run/docker.sock"
      ;;
    *)
      args+=("$1")
      ;;
  esac
  shift
done

set -- "${args[@]}"

docker run --rm -it $user -v "$PWD:$PWD" -v "/etc/localtime:/etc/localtime:ro" -v "/etc/passwd:/etc/passwd:ro" -v "/etc/timezone:/etc/timezone:ro" $docker --workdir "$PWD" "$@"
