#!/bin/bash

GrepAndFilter="ServerName|ServerAlias"

grep --line-buffered -Ei "$GrepAndFilter" /dev/stdin \
    | sed -E "s/^\s*($GrepAndFilter)\s+//gI;s/\s*$//;s/,//g;s/ +/\n/g;s/\n+/\n/g" \
    | rev | sort -u | rev
