#!/bin/bash

usage() {
  echo "Usage: $(basename "$0")"
}

arguments=()
quiet=false

qprintf() {
  printf "%s\n" "$@"
}

qprintfError() {
  qprintf "$@" >&2
}

action="fetch"
while [ "$#" -gt 0 ]; do
  case "$1" in
  "-h" | "--help")
    usage
    exit
    ;;
  "-q" | "--quiet")
    quiet=true
    ;;
  "-p" | "--pull")
    action="pull"
    ;;
  *)
    arguments+=("$1")
    ;;
  esac
  shift
done

set -euo pipefail -- "${arguments[@]}"
IFS=$'\n\t'

if [ "$#" -lt 1 ]; then
  set "$PWD"
fi

actuallyFetch() {
  if [ "$action" = "fetch" ]; then
    flag=("fetch" "-p")
  elif [ "$action" = "pull" ]; then
    flag=("pull")
  else
    exitError 1 "unknown method «$action»"
  fi
  IFS=' '
  qprintf "Calling git ${flag[*]} on $1"
  # shellcheck disable=SC2086
  git -C "$1" ${flag[*]}
}

main() {
  while [ "$#" -gt 0 ]; do
    if [ ! -d "$1/.git" ]; then
      qprintfError "$1 is not a git repository"
    else
      actuallyFetch "${1%/}"
    fi
    shift
  done
}

if "$quiet"; then
  main "$@" >&2 2>/dev/null
else
  main "$@"
fi
