#!/bin/bash

mkdir -p "/tmp/flex"

filename="/tmp/flex/$(random_string 32 'a-zA-Z0-9').yy.c"

if flex -o "$filename" "$1"
then
    if ! gcc "$filename" -lfl
    then
        >&2 echo 'Compilation failed';
    fi
    rm "$filename";
else
    >&2 echo 'Flex failed';
fi


