#!/bin/bash

filename="/tmp/flex$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1).yy.c"

if flex -o "$filename" "$1"
then
    if ! gcc "$filename" -lfl
    then
        >&2 echo 'Compilation failed';
    fi
    rm "$filename";
else
    >&2 echo 'Flex failed';
fi


