#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

usage(){
  echo "usage : $0 [ -d or -D | -C <directory> ]"
  echo "    lists branches that were deleted from remote"
  echo "    -d deletes branches that were deleted from remote (with no unmerged commits)"
  echo "    -D deletes branches that were deleted from remote (even with unmerged commits, when squashing for instance)"
  echo "    -C target behaves like git's -C"

}

if is_help "$@"; then
  usage
  exit
fi

echo "Updating Content ..."
flag=''
gitArgs=()
while test "$#" -gt 0
do
    case "$1" in
        -d)
            flag=d
            ;;
        -D)
            flag=D
            ;;
        -C)
            shift
            gitArgs=("-C" "${1%/}")
            ;;

    esac
    shift
done

git "${gitArgs[@]}" fetch -p

deletedBranches=''
while read -r branch
do
    if [ "$branch" = "*" ];
    then
        echo "Warning: Your current local branch is deleted on remote." >&2
        continue
    fi
    deletedBranches="$deletedBranches, $branch"
    if [ -n "$flag" ]; then
        git "${gitArgs[@]}" branch -$flag "$branch"
    fi
done < <(LANG='' git "${gitArgs[@]}" branch -vv | awk '/: gone/ {print $1}')

if [ -n "$deletedBranches" ]; then
    deletedBranches=${deletedBranches/, }
    if [ -z "$flag" ]; then
        echo "Branches to be trimmed : $deletedBranches"
    else
        echo "Trimed branches : $deletedBranches"
    fi
else
    echo "No branches to trim"
fi
