#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

usage() {
  echo "Usage: gitRemove [ -i  / --interactive | -f / --force ]"
  doc=('-i / --interactive -> dry run' '-f / --force -> remove')
  printf "  %s\n" "${doc[@]}"
}

flag='n'
while [ "$#" -gt 0 ]; do
  case "$1" in
  "-i" | "--interactive")
    flag='i'
    ;;
  "-f" | "--force")
    flag='f'
    ;;
  "-h" | "--help")
    usage
    exit
    ;;
  *)
    exitError 1 "Unknown symbol $1"
    ;;
  esac
  shift
done

if [ "$flag" = 'n' ]; then
  LANG='' git clean -dxne .idea | sed 's#^Would remove # → #'
elif [ "$flag" = 'f' ]; then
  LANG='' git clean -dxfe .idea | sed 's#^Removing # → #'
else
  LANG='' git clean -dx "-$flag" -e .idea
fi
