#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

flag='';
while [ "$#" -gt 0 ]; do
    case "$1" in
        "-n")
            flag='n'
            ;;
        "-f")
            flag='f'
            ;;
        *)
            exitError 1 "Unknown symbol $1"
            ;;
    esac
    shift
done

if [ -z "$flag" ]; then
    exitError 2 "Missing parameter"
fi

git clean -dx "-$flag" -e .idea
