#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

usage(){
    detail "usage : $(basename "$0") [ -d or -D ]"
    doc=(
        "lists branches that were deleted from remote"
        "" "List of flags :"
        "-h | --help displays help"
        "-d deletes branches that were deleted from remote (with no unmerged commits)"
        "-D deletes branches that were deleted from remote (even with unmerged commits, when squashing for instance)"
    )
    detail --printf -- "  %s\n" "${doc[@]}"
}

flag=''
while test "$#" -gt 0
do
    case "$1" in
        "-h"|"--help")
            usage
            exit
            ;;
        -d)
            flag=d
            ;;
        -D)
            flag=D
            ;;
    esac
    shift
done

detail -4 "Updating Content ..."

git fetch -p > /dev/null

deletedBranches=''
while read -r branch
do
    if [ "$branch" = "*" ];
    then
        detail -3 "Warning: Your current local branch is deleted on remote." >&2
        continue
    fi
    deletedBranches="$deletedBranches, $branch"
    if [ -n "$flag" ]; then
        git branch -$flag "$branch" > /dev/null
    fi
done < <(git for-each-ref --format '%(upstream:track) %(refname)' refs/heads | awk ' $1 == "[gone]" { sub("refs/heads/", "", $2) ; print $2 }')

if [ -n "$deletedBranches" ]; then
    deletedBranches=${deletedBranches/, }
    if [ -z "$flag" ]; then
        detail -4 "Branches to be trimmed : $deletedBranches"
    else
        detail -4 "Trimed branches : $deletedBranches"
    fi
else
    detail -4 "No branches to trim"
fi
