#!/usr/bin/env bash

set -euo pipefail

BASENAME=$(basename "$0")

err () {
    printf "\e[31m%s error:\n" "$BASENAME"
    printf "    %s\n" "$@"
    printf "\e[0m"
}

if ! [ -x "$GOPATH/bin/jira" ]; then
    err "\$GOPATH/bin/jira does not exist (GOPATH=$GOPATH)" "You can install it with https://github.com/ankitpokhrel/jira-cli"
    exit 1
fi

if ! command -v 'secret-tool' > /dev/null; then
    err "secret-tool not found." "Try installing it."
    exit 1
fi

JIRA_API_TOKEN=$(secret-tool lookup jira token)

if [ -z "$JIRA_API_TOKEN" ]; then
    err 'Jira token not found in secret-tool.' 'Set it with `secret-tool store --label=global jira token`'
    exit 1
fi

export JIRA_API_TOKEN

$GOPATH/bin/jira "$@"
