#!/bin/bash

set -euo pipefail

app_name=$1

set +e
PID=$(pgrep -n "$1")
set -e

if [ -n "$PID" ]; then
    wmctrl -iR "$(wmctrl -pl | awk "\$3 ~ $PID { print \$1; exit }")"
    exit 0
fi

nohup "$@" >/dev/null 2>&1 &

