#!/bin/bash
    
set -euo pipefail

SOFT="$(basename $0)"

cleanup (){
    :
}

trap cleanup EXIT


while read -r line
do
   echo "$line" | awk -F $'\t' "{printf "$@" }"
done < <(cat /dev/stdin)
    
