#!/usr/bin/env bash

set -euo pipefail

args=()



usage() {
    echo
    echo "$(basename $0): usage"
    echo "$(basename $0) <research>"
    echo
}

while (( $# )); do
    cmd=$1
    shift
    case "$cmd" in
    --help|-h)
        usage
        exit 0
    ;;
    --)
        args+=("$@")
        shift $#
    ;;
    *)
        args+=("$cmd")
        ;;
    esac
done

if ! [ -n "${args[*]}" ]; then
    >&2 echo "$(basename $0) error: missing argument";
    usage
    exit 1;
fi

set -- "${args[@]}"

rg -n "$@" | fzf --cycle --multi --extended
