#!/bin/bash

set -euo pipefail

usage() {
    echo "Usage: $0 filename"
}

if [ "$#" -lt 1 ]; then
    >&2 echo "Error: bad arguments"
    >&2 usage
    exit 1;
fi

if [ "$1" == "-h" -o "$1" == "--help" ]; then
    usage
fi


file="$1"

mkdir -p -- "$(dirname -- "$file")"

if ! [ -f "$file" ]
then
    echo '#!/usr/bin/env bash' >> "$file";
fi

if ! [ -x "$file" ]; then
    chmod a+x "$file"
fi

set +e
2>/dev/null git -C "$(dirname "$1")" add "$(basename "$1")"

editor -- "$file"
