#!/bin/bash

set -euo pipefail

if ! requireArgs 1;then
    echo "Error, Usage : $0 new_file_name" >> /dev/stderr
fi

file="$1"


ensureNotExists () {
    if test -f $file
    then
        echo "File already exists «${file}»"
        exit 1;
    fi
}

ensureNotExists

echo '#!/bin/bash' >> "$file";
chmod +x "$file";
