#!/bin/bash

set -euo pipefail

if test "$#" -lt 1
then
    if test -n "${WORKSPACE-unset}";
    then
        path=$WORKSPACE
    else
        echo Usage : $0 Directory
        exit 2
    fi 
else
    path="$1"
fi

find "$WORKSPACE" -name '.git' -type d -prune -exec bash -c '
action=fetch
tag=-p
base="{}"
name="$(dirname $base)"
cd "$name"
git rev-parse 2> /dev/null || exit
echo -e "\e[92mFetching $(basename "$name") ($base)\e[31m"
git "$action" "$tag"
printf "\e[39m"
' \;
