#!/bin/bash

SOFT="$(basename $0)"

set -euo pipefail

if [ ! "$#" -gt 0 ];then
    echo "usage : $SOFT site_name"
    exit 123;
fi

core="${1%%\.conf}"
document="$WORKSPACE/$core"

if [ "$#" -eq 2 ] && [  "$2" == "fpm" ];then
    findv="$(find /var/run/php* -name 'php*.sock')"
    fpm=$(cat<<EOF 
<FilesMatch \\.php$>
        SetHandler "proxy:unix:$findv|fcgi://$core/"
    </FilesMatch>
    <Proxy fcgi://$core>
        ProxySet connectiontimeout=5 timeout=240
    </Proxy>
    RewriteCond %{REQUEST_FILENAME} \.php$
    RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_URI} ! -f
    RewriteRule (.*) - [H=text/html]
EOF
)
    option='fpm'
elif [ "$#" -gt 2  ] && [ "$2" == 'indirection'  ];then
    document="$WORKSPACE/$3"
    option='indirect'
    fpm='';
else
    fpm=''
    option=''
fi

echo "#making site $core with options : ${option[@]}"



cat <<EOF
<VirtualHost *:80>
    DocumentRoot "$document"
    ServerName ${core}.localhost
    $fpm
    <Directory "$document">
        AllowOverride All
        Options Indexes FollowSymLinks
        Require all granted
    </Directory>
</VirtualHost>
<VirtualHost *:443>
    DocumentRoot "$document"
    ServerName ${core}.localhost
    $fpm
    SSLEngine On
    SSLOptions +FakeBasicAuth +ExportCertData +StrictRequire

    SSLCertificateFile "/var/www/cert/localhost.crt"
    SSLCertificateKeyFile "/var/www/cert/localhost.key"
    <Directory "$document">
        AllowOverride All
        Options Indexes FollowSymLinks
        Require all granted
    </Directory>
</VirtualHost>
EOF
