#!/usr/bin/env bash

set -eo pipefail

DRY_RUN=${DRY_RUN-false}
PREFIX=${PREFIX-}
SOFT=$(basename $0)


normalize() {
  printf "%s%s" "$PREFIX" "$(tr '[:upper:]' '[:lower:]' <<<${1// /_})"
}

while (($#)); do
  case "$1" in
    "--dry-run"|"-n")
      DRY_RUN=true
      shift
      ;;
    "--prefix"|"-p")
      shift
      PREFIX=$1
      shift
      ;;
    *)
      normalized=$(normalize "$1")
      if [ "$1" == "$normalized" ]; then
        echo "$SOFT: already normalized $1"
      else
        if $DRY_RUN; then
          echo mv -v "$1" "$normalized"
        else
          mv -v "$1" "$normalized"
        fi
      fi
      shift
      ;;
  esac
done

