#!/bin/bash

set -euo pipefail

tag='--system'

usage(){
    printf "Error : Usage: $(basename "$0") [$tag] args\n" >> /dev/stderr
    exit 1;
}

testArgs(){
    if test "$#" -lt 1
    then
        usage
        exit  1
    fi
}

testArgs "$@"

if test "$1" == "$tag"
then
    local=false;
    shift
    testArgs "$@" 
else
    local=true;
fi

if $local
then
    find . -regextype sed -regex "$@" -exec phpstorm {} \+ > /dev/null
else
    phpstorm "$(locate --regex "$@" 2> /dev/null)" > /dev/null
fi
