#!/bin/bash

set -euo pipefail

file="/var/lib/pgsql/data/pg_hba.conf"
if ! test -w "$file"
then
	echo "Can't write in file $file" > /dev/stderr
	exit 1;
fi

vim "$file"

echo "Reloading postgresql service ..."
systemctl reload postgresql.service
