#!/bin/bash

SOFT=$(basename $0)

if [ -z ${SQL_USER+x} ]; then
    echo "$SOFT : variable TICKET_SQL_USER not set"
    exit 1
fi
if [ -z ${SQL_PASSWORD+x} ]; then
    echo "$SOFT : variable TICKET_SQL_USER not set"
    exit 2
fi


mysql --user="$SQL_USER" --password="$SQL_PASSWORD" "$@" < /dev/stdin
