#!/bin/bash
    
set -euo pipefail

SOFT="$(basename $0)"

file=$1;
content=$2;

mkdir -p "/tmp/$SOFT"

temp_filename=/tmp/$SOFT/$(basename $file)

rm_temp_file () {
    rm -rf $temp_filename
}

trap rm_temp_file EXIT

echo $content > $temp_filename;
cat $file >> $temp_filename
mv $temp_filename $file
