#!/bin/bash

set -euo pipefail

target="${*: -1}"

array=( "$@" )
unset "array[${#array[@]}-1]"

set -- "${array[@]}"

target=${target%/}

while [ "$#" -gt 0 ]; do
    find "$1" -type d -exec mkdir -p "$target/"{} ';'
    find "$1" -type f -exec mv -n {,"$target/"}{} ';'
    find "$1" -type d -empty -delete
    shift
done
