#!/bin/bash

set -euo pipefail

SOFT="$(basename $0)"

DIRECTORY="."

FILES_TYPE="*.php"


#trap cleanup EXIT

if [ "$#" -lt 2  ];then
    echo "Usage : $SOFT \"recherche\" \"remplacement\""
    exit 1
fi

find "$DIRECTORY" -name "$FILES_TYPE" -not \( -path ./.git -prune -o -path ./.idea -prune  \) -exec refactor_infile "$1" "$2" {} ';'

