#!/bin/bash

set -euo pipefail

if test "$#" -lt 1;
then
    >&2 echo "Error: Usage: $0 <directory>"
    exit 1;
fi

target="$1"

cd "$target"

if ! test -d ".git";
then
    >&2 echo "Error: Directory $target not a git repository"
    exit 2;
fi

echo "Are you sure you want to reset all the history? Make sure there is no work in progress branch. (Undefined behavior)"
while true
do
    read -p "Are you sure ? yes/no
> " yn
    case "${yn,,}" in
        yes ) break;;
        no ) exit 1;;
    esac
done

echo "Removing old history..."

git checkout --orphan newBranch
git add -A
git commit -m "Brand new history"
git branch -D master
git branch -m master
git push -f origin master
git gc --aggressive --prune=all

echo "Done"
