#!/bin/bash

set -euo pipefail

SOFT="$(basename $0)"

resolveHostname(){
    dig +short "$1" | tr '\n' ' '
}


while read -r hostname
do
    realIp="$(resolveHostname $hostname)"
    printf "%-60s %s\n" "$hostname" "$realIp"
done
