#!/bin/bash


set -euo pipefail
mapfile -t branches < <(git branch --format "%(refname:short) %(upstream)" | awk '{ if (!$2) print $1 }')

remote=origin

trackBranch() {
    echo "Setting up remote to $remote/$1"
    git branch --set-upstream-to "$remote/$1" "$1"
}

for branch in "${branches[@]}"; do
    echo "Looking at $branch"
    if
        git ls-remote --exit-code --heads "$remote" "$branch" >/dev/null \
        && (
            git merge-base --is-ancestor "$remote/$branch" "$branch" >/dev/null \
            || git merge-base --is-ancestor "$branch" "$remote/$branch" >/dev/null \
        ) ; then
        trackBranch "$branch"
    elif glab mr list --author=@me --search "$branch" | grep  -P "\($branch\)"; then
        trackBranch "$branch"
    fi
done
