#!/bin/bash
set -euo pipefail
for i in "$WORKSPACE/$HTTPD_NAME/*.conf" ; do 
	echo "$i"
        ln -sf "$i" "/etc/$HTTPD_NAME/conf.d/$(basename $i)";
        servername=$(grep 'ServerName' "$i" | awk '{print $NF}')
        if ! grep -q "$servername"  '/etc/hosts';
        then
            printf "::1\t${servername}\n" >> /etc/hosts
        fi
	if [ "$HTTPD_NAME" != 'httpd'  ]; then
        	a2ensite "$(basename $i)"
	fi
done
systemctl reload $HTTPD_NAME.service
