#!/bin/bash
    
set -euo pipefail

SOFT="$(basename $0)"

err (){
    echo "Error $SOFT : $@"
    exit 127
}

cleanup (){
    :
}

trap cleanup EXIT


declare -A siwipo;

                        
siwipo[danone]='danone.siwipo.fr'
siwipo[pepsi]='pepsi.siwipo.fr'
siwipo[demov2]='demo.siwipo.fr'



main (){
    while (( "$#" ));
    do
        case "$1" in
            list)
                for K in "${!siwipo[@]}"; do echo "$K"; done
                ;;
            convert)
                if [ "${siwipo[$2]+abc}"  ];then
                    echo "${siwipo[$2]}"
                else
                    err "unknown key $2"
                fi
                shift
                ;;
            open)
                while (( "$#" -1 ))
                do
                    navigator "$($SOFT convert $2)";
                    shift
                done
            ;;
            edit)
            vim "$0"
                ;;  
            *)
                err "Unknown Option $1"
            ;;
        esac
        shift
    done
}

main $@

    
