#!/bin/bash

set -euo pipefail


SOFT=$(basename $0)

mkdir -p "/tmp/$SOFT/"

cleanup ()
{
    :
}

trap cleanup EXIT;

exit_error ()
{
    echo "$SOFT : Error $@"
    exit 127
}


sql ()
{
    mysql --user="$TICKET_SQL_USER" --password="$TICKET_SQL_PASSWORD" -h "srv19.siweb.fr"  --database "siweb" --skip-column-names "$@" < /dev/stdin
}


basic_ticket ()
{
    :
}


TICKET_GENERAL_USER=133;

base_sql="SELECT tanum FROM projets_taches WHERE (tauser=$TICKET_USNUM OR taparticipants like '%$TICKET_USNUM%') ";
new_tickets="SELECT IF(tauser=$TICKET_USNUM,'[x]','[ ]'), tanum, ClDesignation1, tanom  FROM projets_taches JOIN clients ON TaClient = ClNum WHERE taetat=1 AND (TaUser IN ($TICKET_GENERAL_USER,$TICKET_USNUM))"


if [ "$#" -lt 1 ]; then
    exit_error "Missing Arguments"
fi


while (( "$#" )); do
    case $1 in
        open)
            shift
            while (( "$#" )); do
                case "$1" in
                    "opened")
                    $SOFT open $($SOFT list opened) # no "" because IFS read one per lines as different arguments
                    ;;
                    "client")
                    shift
                    $SOFT open $($SOFT list $1)
                        ;;
                    *)
                        re='^[0-9]+$'
                        if ! [[ "$1" =~ $re  ]]; then
                            exit_error "Not a number : $1"
                        fi
                    navigator "http://espace-client.siweb.fr/espace-client/support-technique/ticket/$1"
                    ;;
                esac
                shift
            done
            ;;

        edit)
            vim "$0"
            ;;

        list)
            shift 
            if (( "$#" ));then
                if [ -z ${TICKET_USNUM+x} ]; then
                    echo "$SOFT : variable TICKET_SQL_USER not set"
                    exit
                fi
                case "$1" in
                    all)
                    echo "$base_sql AND TaEtat<4 " | sql;
                    ;;

                opened)
                    echo "$base_sql AND taetat=2"  | sql 
                ;;
                new)
                    echo "$new_tickets ORDER BY ClDesignation1" | sql
                ;;
                senlis)
                    echo "$base_sql and taetat<3 and taclient=3251" | sql 
                    ;;
                pepsi)
                    echo "$base_sql and taetat<3 and taclient=373" | sql 
                esac
            fi
            ;;
        vocabulary)

            ;;
        messages)
                
            ;;

        *)
            exit_error "Option inconnue $1"
            ;;

    esac

    shift

done
