#!/bin/bash

set -euo pipefail


SOFT=$(basename $0)

mkdir -p "/tmp/$SOFT/"

cleanup ()
{
    :
}

trap cleanup EXIT;

exit_error ()
{
    echo "$SOFT : Error $@"
    exit 127
}


sql ()
{
    mysql --user="$TICKET_SQL_USER" --password="$TICKET_SQL_PASSWORD" -h "srv19.siweb.fr"  --database "siweb" "$@" < /dev/stdin
}


if [ "$#" -lt 1 ]; then
    exit_error "Missing Arguments"
fi


while (( "$#" )); do
    case $1 in
        open)
            shift
            if ! (( "$#" ));then
                exit_error "Missing arguments after open"
            fi
            if [ "$1" == "opened"  ];then
                $SOFT open $($SOFT list opened) # no "" because IFS read one per lines as different arguments
                break;
            fi
            while (( "$#" )); do
                xdg-open "http://espace-client.siweb.fr/espace-client/support-technique/ticket/$1" &> /dev/null &
                shift
            done
            ;;
        edit)
            vim "$0"
            ;;
        list)
            shift 
            if (( "$#" ));then
                if [ -z ${TICKET_USNUM+x} ]; then
                    echo "$SOFT : variable TICKET_SQL_USER not set"
                    exit
                fi
                case "$1" in
                    all)
                    echo "SELECT tanum FROM projets_taches WHERE TaEtat<4 AND (TaEtat=1 OR TaUser=$TICKET_USNUM)" | sql  --skip-column-names;
                    ;;

                opened)
                    echo "SELECT tanum FROM projets_taches WHERE tauser=$TICKET_USNUM AND taetat=2"  | sql --skip-column-names

                esac
            fi
            ;;
        vocabulary)

            ;;

        *)
            exit_error "Option inconnue $1"
            ;;

    esac

    shift

done
