#!/bin/bash

set -euo pipefail

if ! git rev-parse 2> /dev/null
then
    echo "Error : not in a git repository" > /dev/stderr
    exit 1;
fi

lookFor="phpunit.xml"

topLevel=$(git rev-parse --show-toplevel)
count=false

while IFS= read -r -d $'\0' line
do
    count=true
    echo "Executing tests for configuration file «$line»"
    phpunit --configuration "$line"
done  < <(find "$topLevel" -not \( -path "*vendor*" -prune \) -name "$lookFor" -print0)

if ! "$count"
then
    echo "No tests configuration files ($lookFor)  were found in $topLevel" >> /dev/stderr
    exit 2;
fi

