#!/bin/bash

set -euo pipefail

source=$1
target=$2


rsyncWrap(){
    rsync -avzq --delete --exclude-from=$HOME/.rsyncignore "$source" "$target"
}

rsyncWrap
while inotifywait -r -e modify,create,delete,move "$source"; do
    rsyncWrap
done

exit
"Documentation

You have to install rsync and inotify-tools


Usage : $0 source target &
