#!/bin/bash

usage="Usage : $0 source target &"

if ! which rsync >> /dev/null
then
    echo "Can't find rsync, please install it and verify your PATH" >> /dev/stderr
    exit 2;
fi

if ! which inotifywait >> /dev/null
then
    echo "Can't find inotifywait, please install inotify-tools and verify your PATH" >> /dev/stderr
    exit 3
fi

rsyncignore="$HOME/.rsyncignore"

if ! test -f "$rsyncignore"; then
    echo "File ~/.$(basename $rsyncignore) does not exist, aborting ..." >> /dev/stderr
    exit 4
fi

if test "$#" -lt 2
then
    echo "$usage" >> /dev/stderr
     exit 1;
fi


source=$1
target=$2

log () {
    logger -t "$(basename $0)" "$@"
}

log starting $(basename $source)

rsyncWrap(){
    timeout 5 rsync -avzq --delete --exclude-from="$rsyncignore" "$source" "$target"
    retour=$?
    if ! test $retour -eq 0; then
        log Erreur dans le retour de rsync: $retour
    fi
}

flag=true

toggleFlag(){
    flag=false
}

trap toggleFlag SIGTERM

rsyncWrap
while $flag && inotifywait -q -r -e modify,create,delete,move "$source" ; do
    rsyncWrap
done

log ending $(basename $source)
