#!/bin/bash

SPATH=$(echo "$PATH" | grep -oE ":.*symfony:")
SPATH=${SPATH/:}
SPATH=${SPATH%:}
cd "$SPATH"

while [ "$#" -gt 0 ]; do
    printf "#!/bin/bash\n\nsymfony_console \"%s:\$@\"" "$1" > "$1"
    chmod a+x "$1"
    shift
done
