#!/bin/bash

SOFT=$(basename $0)

if [ -z ${CVS_REMOTE_PASSWORD+x}  ];then
    echo "$SOFT : Undefined variable CVS_REMOTE_PASSWORD"
    exit 1;
fi

if [ -z ${CVS_REMOTE_CVSROOT+x}  ];then
    echo "$SOFT : Undefined variable CVS_REMOTE_CVSROOT"
    exit 1;
fi

if [ "$#" -lt 2  ]; then
    echo "$SOFT usage : $SOFT cvs_module_path cvs_module_name"
    exit 1;
fi

version="prod";

while getopts ":t:" option
do
    case "$option" in
        t)
            shift
            version="$1";
            shift
            ;;
    esac
done

remote_dir="$1"
module="$2"
prompt="prompt>"

mkdir -p "/tmp/$SOFT"
filename="/tmp/$SOFT/$module"

function write_password() {
    echo "expect \"Password:\" {send \"$CVS_REMOTE_PASSWORD\n\"}" >> $filename
}

echo "#!/usr/bin/expect" > $filename
cleanup (){
    :
    #rm $filename
}


cvs_update_f () {
    fake='';
    while getopts ":n:" option
    do
        case "$option" in
            n)
                fake='-n'
                shift
                ;;
        esac
    done
    echo "send \"cvs update -d -q -P${fake} ${@} \n\"" >> $filename
}

trap cleanup EXIT
cat <<EOD >> $filename
spawn ssh srv11
send "PS1='$prompt'\n";
send "CVSROOT='$CVS_REMOTE_CVSROOT'\n";
expect "$prompt"
send "cd $remote_dir\n"
EOD

write_password;


if [ "$is_test_version" = "test" ]; then
    cvs_update_f $module
else
    cvs_update_f -n $module
fi

cat <<EOD >> $filename
expect "$prompt"
send "logout\n"
expect eof
EOD

chmod +x $filename

echo "Starting update of $module"

#$filename
cat $filename

printf "\nEnd of update\n"
