#!/bin/bash
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "HEAD" ]; then
    exit 0;
fi

    message=$(cat "$1")

if [[ $message == ${branch}* ]]; then
    exit 0;
fi

echo "$branch - $message" > "$1"

